---
- hosts: all

  vars:
    username: oracle
    user_default_password: Welcome1
    enable_sudo: yes
    enable_passwordless_sudo: yes
    ssh_keyfile: id_rsa.pub

  tasks:

    - name: add user account with access to sudo
      user:
        name: "{{ username }}"
        password: "{{ user_default_password | password_hash('sha512') }}"
        comment: Ansible created user
        groups: wheel
        append: yes
        update_password: on_create

    - name: set authorized key for user using local pubilc key file
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/{{ ssh_keyfile }}') }}"

    - name: set user with passwordless sudo access
      lineinfile:
        path: /etc/sudoers.d/oracle
        regexp: '{{ username }} ALL='
        line: '{{ username }} ALL=(ALL:ALL) NOPASSWD: ALL'
        state: present
        create: yes
