---
- hosts: all

  tasks:

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print ansible_distribution
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} is running {{ ansible_distribution }} on version {{ distribution_major_version }}
