---
- hosts: all
  become: yes

  tasks:
    - name: install python sdk on Oracle Linux 8
      ansible.builtin.dnf:
        name: "python36-oci-sdk"
        state: latest
      when: ansible_distribution == 'OracleLinux' and (ansible_facts['distribution_version'] is version('8', '>='))
