---
- hosts: all
  become: yes
  tasks:
  - name: Check if the aide database exists
    stat:
      path: /var/lib/aide/aide.db.gz
    register: p
  - name: Fail if aide database exists
    fail:
      msg: The aide database exists, therefore aide is installed, we need to exit
    when: p.stat.exists
  - name: Install aide package
    yum:
      name: aide
      state: present
  - name: Initialise aide
    command: aide --init
    register: command_output
  - debug: var=command_output
  - name: Enable Database for aide
    command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
