---
#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to create a VM using Oracle Linux Virtualization Manager (OLVM)
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
olvm_fqdn: ovirt.it.oracle.com
olvm_user: shayler@internal
olvm_cafile: /etc/pki/ovirt-engine/ca.pem

# Variables applicable to all vms
# 
# OLVM VM create details
#
olvm_cluster: cluster03
olvm_template: OL8U6_x86_64-olvm-b126_NODE03
vm_ram: 512MiB
 
# Cloud init variables
#
vm_dns: 192.168.100.2
vm_dns_domain: example.com
vm_gateway: 192.168.100.1
vm_netmask: 255.255.255.0
vm_timezone: Europe/London
vm_hostname: vm01.example.com
vm_ip_address: 192.168.100.41

---
- hosts: all
  become: yes
  #become_method: sudo
  #gather_facts: no
  vars_files:
    - /var/lib/awx/projects/files/ovirt_passwords.yaml
    
  tasks:
    - name: Login to OLVM manager
      ovirt_auth:
        hostname: "{{ olvm_fqdn }}"
        username: "{{ olvm_user }}"
        password: "{{ olvm_password }}"
        ca_file: "{{ olvm_cafile | default(omit) }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always
    - name: Create Virtual Machine
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ olvm_cluster | default('Default') }}"
        template: "{{ olvm_template }}"
        name: "{{ item }}"
        state: running
        memory: "{{ vm_ram }}"
        high_availability: yes
        cloud_init:
          host_name: "{{ hostvars[item]['ansible_host'] }}"
          user_name: root
          root_password: "{{ vm_root_passwd }}"
          dns_servers: "{{ vm_dns }}"
          dns_search: "{{ vm_dns_domain }}"
          nic_name: "{{ vm_nicname | default('eth0') }}"
          nic_on_boot: true
          nic_boot_protocol: static
          nic_ip_address: "{{ vm_ip_address }}"
          nic_gateway: "{{ vm_gateway }}"
          nic_netmask: "{{ vm_netmask }}"
          timezone: "{{ vm_timezone }}"
          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ vm_hostname }}
              - yum -y remove cloud-init
      
    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
