---
- hosts: all
  tasks:
  - name: Remove apache packages 
    yum:
      name: httpd
      state: absent
  - name: Remove port 80
    firewalld:
      service: http
      permanent: true
      state: disabled
