---
- hosts: all
  become: yes
  vars:
    use_proxy: no
    proxy: '{{ proxy_host|default(omit) }}:{{ proxy_port|default(omit) }}'
    proxy_env:
      http_proxy: '{{ proxy }}'
      https_proxy: '{{ proxy }}'
      ftp_proxy: '{{ proxy }}'
      no_proxy: '{{ no_proxy_list | default(omit) }}'

  tasks:
    - name: update all packages on all Oracle Linux 8 systems
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'OracleLinux' and (ansible_facts['distribution_version'] is version('8', '>='))

    - name: update all packages on all Oracle Linux 7 systems
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'OracleLinux' and (ansible_distribution_version is version ('7', '<'))

    - name: update all packages on all Oracle Linux 6 systems
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'OracleLinux' and (ansible_distribution_version is version ('6', '<'))

    - name: check if reboot required
      command: /usr/bin/needs-restarting -r
      register: reboot_required
      ignore_errors: yes
      changed_when: false
      failed_when: reboot_required.rc == 2
      when: ansible_distribution == 'OracleLinux'

    - debug:
        var: reboot_required

    - name: reboot (if needed) to apply latest kernel and updates
      reboot:
      when: ansible_distribution == 'OracleLinux' and reboot_required.rc == 1

  environment: "{{ proxy_env | default(omit) }}"
