---
- hosts: all
  become: yes
  vars:
    use_proxy: no

  tasks:
    - name: create proxy for apt-get
      copy:
        dest: "/etc/apt/apt.conf.d/10proxy.conf"
        content: |
          Acquire {
            http::Proxy "http://{{ proxy_server }}:{{ proxy_port }}";
            https::Proxy "http://{{ proxy_server }}:{{ proxy_port }}";
          }
      when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and use_proxy

    - name: update apt repo and cache (apt-get update) on all debian/ubuntu systems
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: upgrade all packages (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: check if reboot needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - debug:
        var: reboot_required_file

    - name: reboot system if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
      when:
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and reboot_required_file.stat.exists
